name: Felipe en 🇩🇰
author: Felipe Cabargas
baseurl:
description: Otro 🇨🇱 en Dinamarca
github: http://www.github.com/felipecabargas
twitter: http://www.twitter.com/juanpintoduran
instagram: http://www.instagram.com/juanpintoduran
linkedin: http://www.linkedin.com/in/cabargas
email: felipe.cabargas[at]gmail.com
location: København, Danmark
disqus: cabargas

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
